### ISSUE TITLE
sliding dtilts adjustments (late hit hitbox size)

### ISSUE THREAD

**Issue by JoaoAlmeida20** [HDR-Development/HewDraw-Remix#483]
In hdr, most sliding d-tilts are pretty powerful moves, for a lot of them it's not hard to argue that they might need some tuning down in some aspects.
A big contributor to this is that they have the late hit hitbox's size matching the early hit, unlike vanilla where most late hits are smaller
This makes challenging recoveries at ledge too easy, as these moves often linger for a long time and with the bigger hitbox they can often trade with the recovery over and over or just straight up win because of how big some of these hitboxes are, and confirm into a kill. It also makes challenging these moves from above harder than it looks at times, which seems unnecessary.

A list of characters with sliding d-tilts to look at (not necessarily meaning I'm suggesting all of these should have changes):

- [x] King Dedede (Addressed by #1642)
- [ ] Mega Man
- [ ] Cloud
- [x] Simon
- [x] Richter
- [x] Joker (Addressed by #2103)
- [x] Banjo (Addressed by #457) 
- [x] Min Min (Addressed by #1809)
- [x] Sephiroth (Addressed by #482)

**Comment by MadVillainLordQ** [comment]
Cloud's dtilt does become smaller during its later active frames.

**Comment by moklmaru** [comment]
The majority of these characters' down tilts have now been addressed as deemed necessary at this current time
